name = "ABCTrueAlmostAlways"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ABCTrueAlmostAlways"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.20.0"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[lean_lib]]
name = "ABCTrueAlmostAlways"
